dist: xenial

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
    pip install tox-travis flake8
script:
    - tox
    - flake8 tornado_coroutines_opentracing/ tests/
